name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Deploy via SSH
      uses: easingthemes/ssh-deploy@v4.3.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET_PATH: ${{ secrets.REMOTE_PATH }}
      with:
        localPath: dist/
        port: 22
